version: "3.8"
services:
  nginxproxymanager:
    image: "jc21/nginx-proxy-manager"
    container_name: nginxproxymanager
    restart: unless-stopped
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - ./path-to-/data:/data
      - ./path-to-/letsencrypt:/etc/letsencrypt
