---
services:
  jellyfin:
    image: linuxserver.io/jellyfin
    container_name: jellyfin
    volumes:
      - ./config:/config
      - ./cache:/cache
      - ./media/Movies:/Movies
      - ./media/Anime:/Anime
      - ./media/Series:/Series
    ports:
      - 8097:8096
    restart: "unless-stopped"
    environment:
      - PUID=501
      - PGID=20
