version: "3.8"
services:
  jellyfin:
    image: linuxserver.io/jellyfin
    container_name: jellyfin
    volumes:
      - ./path-to-/config:/config
      - ./path-to-/cache:/cache
      - /path-to-media/:/Movies
      - /path-to-media/:/Anime
      - /path-to-media/:/Series
    ports:
      - 8097:8096
    restart: "unless-stopped"
    environment:
      - PUID=501
      - PGID=20
